replicaCount: 1

appName: sumana

backend:
  image: apit:latest
  replicas: 2
  port: 8081
  memory: 512Mi
  cpu: 250m

frontend:
  image: frontend:latest
  replicas: 2
  port: 80
  memory: 300Mi
  cpu: 200m
  dbUrl: jdbc:mysql://host.docker.internal:3306/test_motors_db?createDatabaseIfNotExist=true

sql:
  image: mysql:latest
