# apiVersion: networking.k8s.io/v1
# kind: Ingress



# apiVersion: v1
# kind: Service
# metadata:
#   name: sumana-nodeport
# spec:
#   type: NodePort
#   selector:
#     app: sumana-frontend
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#       nodePort: 30080
# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: sumana-backend-nodeport
# spec:
#   type: NodePort
#   selector:
#     app: sumana-backend
#   ports:
#     - protocol: TCP
#       port: 8081
#       targetPort: 8081
#       nodePort: 32081