apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sumana-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  tls:
    - hosts:
        - sumana.local
        - api.sumana.local
      secretName: sumana-tls-secret
  rules:
    - host: sumana.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.appName}}-frontend
                port:
                  number: {{ .Values.frontend.port }}
    - host: api.sumana.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.appName}}-backend
                port:
                  number: {{ .Values.backend.port }}

# apiVersion: v1
# kind: Service
# metadata:
#   name: sumana-nodeport
# spec:
#   type: NodePort
#   selector:
#     app: sumana-frontend
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80
#       nodePort: 30080
# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: sumana-backend-nodeport
# spec:
#   type: NodePort
#   selector:
#     app: sumana-backend
#   ports:
#     - protocol: TCP
#       port: 8081
#       targetPort: 8081
#       nodePort: 32081